server:
  port: 8080

spring:
  application:
    name: gateway-zuu
  cloud:
    gateway:
      routes:
      - id: course-edge-service
        uri: http://lb.idig88.com:10004
        predicates:
        - Path=/course/**
      - id: user-edge-service
        uri: http://lb.idig88.com:10003
        predicates:
        - Path=/user/**

logging:
  level:
    org.springframework.cloud.gateway: debug